name: neurolang_gallery deploy trigger

on:
  push:
    branches:
      - master
      
jobs:
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment to server
        run: |
          curl -X POST \
          -F token=$DEPLOY_TRIGGER_TOKEN \
          -F ref=master \
          -F "variables[REPO]=neurolang_gallery" \
          https://gitlab.inria.fr/api/v4/projects/25219/trigger/pipeline
